[package]
name = "lsp-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bimap = "0.6"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["visit"] }
